### ISSUE TITLE
bad title tag and not respecting spacing

### ISSUE THREAD

**Issue by noraj** [blackmiaool/gulp-markdown-table-to-json#3]
I was trying your example.

Instead of using:

```markdown
###### boys
name | age| grade 
-----|----|-----
John|11|3
Bob|13|4

###### girls
name | age| grade | 
-----|----|-----
Petra|15|8
Olivia|14|7
```

I used:

```markdown

###### boys
name | age| grade 
-----|----|-----
John|11|3
Bob|13|4

###### girls

name | age| grade | 
-----|----|-----
Petra|15|8
Olivia|14|7
```

And this output `{}`.

I guessed you used 6 `#` (`######`) because valid markdown use only h1 to h5 but you didn't said that in your documentation. But the default of your application should be using something invisible like `<!-- md2json: boys -->` else it will be rendered in the markdown file.

Also this should have the possibility to be one or several blank lines between the table and the title tag.

**Comment by blackmiaool** [comment]
Fixed

**Comment by noraj** [comment]
55c7ef6e6dea0ebd3dd3ba6261bfd4d462415bf5
