### ISSUE TITLE
no link processing

### ISSUE THREAD

**Issue by noraj** [blackmiaool/gulp-markdown-table-to-json#4]
The application badly process markdown links.

Instead of keeping links value `https://example.org` and `http://test.com`, it keeps the raw markdown text `[John][john]` and `[Petra](https://example.org)`, which is, of course, undesirable.

input

```markdown
###### boys
name | age| grade 
-----|----|-----
[John][john]|11|3
Bob|13|4

###### girls
name | age| grade | 
-----|----|-----
[Petra](https://example.org)|15|8
Olivia|14|7

[john]:http://test.com
```

output

```json
{"boys":[{"name":"[John][john]","age":"11","grade":"3"},{"name":"Bob","age":"13","grade":"4"}],"girls":[{"name":"[Petra](https://example.org)","age":"15","grade":"8"},{"name":"Olivia","age":"14","grade":"7"}]}
```

**Comment by blackmiaool** [comment]
User should handle the content by themselves. For example, they want the **https://example.org** but not the name.
